name: Upstream Sync

# 关键修复：增加workflows写入权限
permissions:
  contents: write
  workflows: write  # 新增此行解决工作流文件更新权限问题

on:
  schedule:
    - cron: "0 4 * * *" # At 12PM UTC+8
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 添加深度克隆确保完整历史记录

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: LibreSpark/LibreTV
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 添加强制覆盖选项解决文件冲突
          git_push_force: false
          git_reset_hard: true

      # 更新错误信息使其更准确
      - name: Sync check
        if: failure()
        run: |
          echo "::error::[同步失败] 可能原因："
          echo "1. 工作流文件权限不足（已修复本次配置）"
          echo "2. 上游仓库分支保护规则变更"
          echo "3. 同步出现文件冲突"
          echo "请手动检查：https://github.com/LibreSpark/LibreTV/compare/main...$(git rev-parse --abbrev-ref HEAD)"
          exit 1
