name: Upstream Sync

# 修复后的权限配置
permissions:
  contents: write
  actions: write  # 正确的权限名称应该是 'actions'

on:
  schedule:
    - cron: "0 4 * * *" # At 12PM UTC+8
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保获取完整历史记录

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: LibreSpark/LibreTV
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync check
        if: failure()
        run: |
          echo "::error::[同步失败] 请手动执行同步:"
          echo "1. 前往你的仓库: https://github.com/${{ github.repository }}"
          echo "2. 点击 'Sync fork' 按钮"
          echo "3. 选择 'Update branch'"
          exit 1
